#!/usr/bin/env bash

CWD=$(pwd) 
DATE=$(date +"%Y%m%d%H%M")

# clear old symlink or backup old nvim dir, if it exists
if [ -h $HOME/.config/nvim ] ; then
  echo "Removing stale symlink ~/.config/nvim"
  rm $HOME/.config/nvim
elif [ "$CWD" != "$HOME/.config/nvim" ] ; then
  # output links
  echo "Creating symlink ~/.config/nvim to $CWD"
  ln -s $CWD $HOME/.config/nvim
fi

# create dirs
mkdir -p $HOME/.config/nvim/{tmp,undo,view}
# install submodues and init
git submodule init
wait
git submodule foreach git pull origin master
wait
git submodule update --init --recursive
wait
printf "All done!\n"
